# Generated by Django 5.2.8 on 2025-12-08 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mincredit', models.FloatField(default=0)),
                ('maxlesson', models.IntegerField(default=100)),
            ],
        ),
    ]
