# Generated by Django 5.2.8 on 2025-12-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0014_alter_lesson_options_remove_course_crss_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
