# Generated by Django 5.2.8 on 2025-12-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('cn', models.CharField(max_length=100, verbose_name='cn')),
                ('en', models.CharField(max_length=100, verbose_name='en')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('dateTimePlaceText', models.CharField(blank=True, max_length=100, null=True)),
                ('dateTimePlacePersonText', models.JSONField()),
                ('teacherAssignmentList', models.JSONField()),
                ('campus', models.JSONField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='choice.course')),
            ],
        ),
    ]
