# Generated by Django 5.2.8 on 2025-12-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='choice.course')),
            ],
            bases=('choice.course',),
        ),
        migrations.RemoveField(
            model_name='course',
            name='en',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='dateTimePlacePersonText',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='dateTimePlaceText',
        ),
        migrations.AddField(
            model_name='lesson',
            name='nw',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='choice.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='select',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select', to='choice.select'),
        ),
    ]
