# Generated by Django 5.2.8 on 2025-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_select_remove_course_en_remove_lesson_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='select',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Select',
        ),
    ]
