# Generated by Django 5.2.8 on 2025-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0003_alter_lesson_select_delete_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='abc',
            field=models.FloatField(default=0),
        ),
    ]
