# Generated by Django 5.2.8 on 2025-12-05 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0004_courses_course_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='abc',
        ),
        migrations.AddField(
            model_name='course',
            name='crss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rlt', to='choice.courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='maxlesson',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='mincredit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
