# Generated by Django 5.2.8 on 2025-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0005_remove_course_abc_course_crss_courses_maxlesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='mincredit',
            field=models.FloatField(default=0),
        ),
    ]
