# Generated by Django 5.2.8 on 2025-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0006_alter_courses_mincredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='maxlesson',
            field=models.IntegerField(default=100),
        ),
    ]
