# Generated by Django 5.2.8 on 2025-12-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0007_alter_courses_maxlesson'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rlt', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
