# Generated by Django 5.2.8 on 2025-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0008_alter_course_crss_lesson_rating_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='dateTimePlace',
            field=models.JSONField(null=True),
        ),
    ]
