# Generated by Django 5.2.8 on 2025-12-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0009_lesson_datetimeplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='dateTimePlace',
            new_name='dateTimePlaceText',
        ),
    ]
