# Generated by Django 5.2.8 on 2025-12-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0010_rename_datetimeplace_lesson_datetimeplacetext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['rating']},
        ),
    ]
