# Generated by Django 5.2.8 on 2025-12-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0011_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-rating']},
        ),
    ]
