# Generated by Django 5.2.8 on 2025-12-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0013_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='crss',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='select',
        ),
    ]
